export default [
    {
        name: 'John Adams',
        image: '/images/people/person0.jpg',
        rating: 102,
        ideas: 0,
        following: 52,
        followers: 0,
        marked: false,
    },
    {
        name: 'Kevin Malcolm',
        image: '/images/people/person1.jpg',
        rating: 1472,
        ideas: 20,
        following: 19,
        followers: 26,
        marked: false,
    },
    {
        name: 'James Madison',
        image: '/images/people/person2.jpg',
        rating: 32,
        ideas: 0,
        following: 2,
        followers: 0,
        marked: true,
    },
    {
        name: 'James Monroe',
        image: '/images/people/person3.jpg',
        rating: 3086,
        ideas: 53,
        following: 1059,
        followers: 45,
        marked: true,
    },
    {
        name: 'Andrew Jackson',
        image: false,
        rating: 102,
        ideas: 0,
        following: 50,
        followers: 0,
        marked: false,
    },
];
